"""P104 refactor: omo_governance_surfaces snapshots 子模块 (从 omo_governance_surfaces.py 提取).

ADR-0097 负面登记: 13 god-module TS/Python 待拆, Python 中最大 1762L.
P104 决策: 拆 omo_governance_surfaces.py 的 2 个纯数据 snapshot 函数.

2 个 snapshot 函数 (合计 505L, god-module 文件最大 2 函数):
  - _mutation_surface_registry_snapshot (L626-910, 284L): 28 governance mutation surface registry
  - _worker_internal_write_profiles_snapshot (L919-1140, 221L): 8 worker internal write profile

特性: 2 函数都是 pure data (`return [{...}, {...}, ...]` literal dict lists)
     零外部依赖 (无 Path/yaml/import), 4 个内部 call site 都 snapshot() 无参调用.

模块依赖: 零 (纯 stdlib types hint).

向后兼容 (P88/P100/P101/P102/P103 模式):
  omo_governance_surfaces.py 通过 `from .omo_governance_surfaces_snapshots import (...)` re-export,
  保持 `_mutation_surface_registry_snapshot()` 等函数签名不破.

P104 收益:
  - omo_governance_surfaces.py 1762L → ~1257L, <1500L god-module threshold
  - 13 god-module 列表: Python 3 → 2 (剩 omo_ingress_task_lifecycle 1530L + domain_manager 1914L)
  - P105+ 推进 omo_ingress_task_lifecycle + domain_manager
"""

from __future__ import annotations


def _mutation_surface_registry_snapshot() -> list[dict[str, object]]:
    return [
        {
            "name": "omo-governance-ingress-goal",
            "entrypoint": "omo governance ingress-goal",
            "runtime_ref": "projects/omo/src/omo/omo_governance.py:main (command=ingress-goal)",
            "mutation_target": ".omo/goals/current.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_goal",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/goals/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-governance-ingress-task",
            "entrypoint": "omo governance ingress-task",
            "runtime_ref": "projects/omo/src/omo/omo_governance.py:main (command=ingress-task)",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-governance-ingress-debt",
            "entrypoint": "omo governance ingress-debt",
            "runtime_ref": "projects/omo/src/omo/omo_governance.py:main (command=ingress-debt)",
            "mutation_target": ".omo/debt/items/ + .omo/debt/registry.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:upsert_debt_item",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/debts/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-goal-create",
            "entrypoint": "omo goal create",
            "runtime_ref": "projects/omo/src/omo/omo_goal.py:cmd_goal_create",
            "mutation_target": ".omo/goals/current.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_goal",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/goals/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-goal-progress",
            "entrypoint": "omo goal progress",
            "runtime_ref": "projects/omo/src/omo/omo_goal.py:cmd_goal_progress",
            "mutation_target": ".omo/goals/current.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:update_goal_progress",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/goals/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-task-create",
            "entrypoint": "omo task create",
            "runtime_ref": "projects/omo/src/omo/omo_task.py:cmd_task_create",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-task-done",
            "entrypoint": "omo task done",
            "runtime_ref": "projects/omo/src/omo/omo_task.py:cmd_task_done",
            "mutation_target": ".omo/tasks/active/|planned/ -> .omo/tasks/done/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:complete_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-task-refresh-evidence",
            "entrypoint": "omo task refresh-evidence",
            "runtime_ref": "projects/omo/src/omo/omo_task.py:cmd_task_refresh_evidence",
            "mutation_target": ".omo/tasks/done/*.yaml (evidence_paths)",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:update_done_task_evidence_paths",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-task-repair-approval",
            "entrypoint": "omo task repair-approval",
            "runtime_ref": "projects/omo/src/omo/omo_task.py:cmd_task_repair_approval",
            "mutation_target": ".omo/tasks/{planned,active,done,remediation}/*.yaml (approval_ref) + .omo/workers/runs/*-promotion-approval-*.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:repair_task_promotion_approval",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-worker-task-normalize-planned",
            "entrypoint": "uv run python -m omo.cli worker task normalize-planned",
            "workdir": "projects/omo",
            "runtime_ref": "projects/omo/src/omo/omo_worker_cmd_task.py:execute_task_command (task_command=normalize-planned)",
            "mutation_target": ".omo/tasks/planned/ + .omo/tasks/archived/legacy-normalized/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:normalize_legacy_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-worker-task-route-self-evolution-remediation",
            "entrypoint": "uv run python -m omo.cli worker task route-self-evolution-remediation",
            "workdir": "projects/omo",
            "runtime_ref": "projects/omo/src/omo/omo_worker_cmd_task.py:execute_task_command (task_command=route-self-evolution-remediation)",
            "mutation_target": ".omo/tasks/planned/ -> .omo/tasks/remediation/ + .omo/tasks/remediation-notes/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:route_self_evolution_to_remediation",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "opc-p6-self-evolve-task-emit",
            "entrypoint": "python3 scripts/opc_p6_self_evolve.py",
            "runtime_ref": "projects/omo/src/omo/omo_self_evolve.py:write_planned_self_evolution_tasks",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-knowledge-add",
            "entrypoint": "omo knowledge add",
            "runtime_ref": "projects/omo/src/omo/omo_knowledge.py:cmd_knowledge_add",
            "mutation_target": ".omo/_knowledge/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_knowledge_doc",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/knowledge/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-standard-add",
            "entrypoint": "omo standard add",
            "runtime_ref": "projects/omo/src/omo/omo_standard.py:cmd_standard_add",
            "mutation_target": ".omo/standards/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_standard_doc",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/standards/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-capability-registry-scan",
            "entrypoint": "omo-capability capability scan --write",
            "runtime_ref": "projects/omo/src/omo/omo_capability.py:scan_command",
            "mutation_target": ".omo/capabilities/INDEX.md + .omo/capabilities/projects-capabilities.yaml + .omo/capabilities/sharedwork-sample.yaml + .omo/capabilities/system-packages.yaml + .omo/capabilities/agent-clis.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:write_capability_registry_bundle",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/capabilities/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-capability-registry-register",
            "entrypoint": "omo-capability capability register <file>",
            "runtime_ref": "projects/omo/src/omo/omo_capability.py:register_command",
            "mutation_target": ".omo/capabilities/manual-capabilities.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:write_manual_capabilities",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/capabilities/",
            "mode": "brokered",
            "category": "human_cli",
        },
        {
            "name": "omo-task-center-skill-manifest",
            "entrypoint": "projects/omo/src/omo/omo_skill.py:register_skill_manifest",
            "runtime_ref": "projects/omo/src/omo/omo_skill.py:register_skill_manifest",
            "mutation_target": ".omo/_truth/task-center/skills/*.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_skill_manifest",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/task-center/skills/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-task-center-discovery-registry",
            "entrypoint": "projects/omo/src/omo/omo_discovery.py:discover_task_blueprints",
            "runtime_ref": "projects/omo/src/omo/omo_discovery.py:discover_task_blueprints",
            "mutation_target": ".omo/_truth/task-center/discovery-registry.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:write_discovery_registry",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/task-center/discovery/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-self-healing-debt",
            "entrypoint": "projects/omo/src/omo/omo_self_healing.py:SelfHealingEngine._create_debt",
            "runtime_ref": "projects/omo/src/omo/omo_self_healing.py:SelfHealingEngine._create_debt",
            "mutation_target": ".omo/debt/items/*.yaml + .omo/_truth/registry/debt.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:upsert_debt_item",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/debts/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-bridge-bmad-openspec",
            "entrypoint": "omo bridge --format bmad|openspec",
            "runtime_ref": "projects/omo/src/omo/omo_bridge.py:_import_bmad",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "bridge_import",
        },
        {
            "name": "omo-bridge-fast-track",
            "entrypoint": "omo bridge --format fast_track",
            "runtime_ref": "projects/omo/src/omo/omo_bridge.py:_import_fast_track",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "bridge_import",
        },
        {
            "name": "omo-bridge-pitch",
            "entrypoint": "omo bridge --format pitch",
            "runtime_ref": "projects/omo/src/omo/omo_bridge.py:_import_pitch",
            "mutation_target": ".omo/goals/current.yaml + .omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_goal.py:cmd_goal_create + projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/goals/ + runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "bridge_import",
        },
        {
            "name": "ecos-mof-state-bridge-m1-to-omo",
            "entrypoint": "python3 projects/ecos/src/ecos/ssot/tools/mof-state-bridge.py --m1-to-omo",
            "runtime_ref": "projects/ecos/src/ecos/ssot/tools/mof-state-bridge.py:main (flag=--m1-to-omo)",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "bridge_import",
        },
        {
            "name": "c2g-storage-save-bet",
            "entrypoint": "projects/c2g/src/c2g/adapters.py:EcosStorageProvider.save_bet",
            "runtime_ref": "projects/c2g/src/c2g/adapters.py:EcosStorageProvider.save_bet",
            "mutation_target": ".omo/goals/current.yaml",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_goal",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/goals/",
            "mode": "brokered",
            "category": "c2g_adapter",
        },
        {
            "name": "c2g-storage-save-task",
            "entrypoint": "projects/c2g/src/c2g/adapters.py:EcosStorageProvider.save_task",
            "runtime_ref": "projects/c2g/src/c2g/adapters.py:EcosStorageProvider.save_task",
            "mutation_target": ".omo/tasks/planned/",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:create_planned_task",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/tasks/",
            "mode": "brokered",
            "category": "c2g_adapter",
        },
        {
            "name": "omo-state-refresh",
            "entrypoint": "omo state refresh",
            "runtime_ref": "projects/omo/src/omo/omo_state.py:cmd_state_refresh",
            "mutation_target": ".omo/state/runtime/system_health.yaml + .omo/state/system_health.yaml",
            "broker_ref": None,
            "delivery_artifact_root": None,
            "mode": "direct-runtime-cache",
            "category": "runtime_cache",
        },
        {
            "name": "omo-state-sync-tasks",
            "entrypoint": "omo state sync-tasks",
            "runtime_ref": "projects/omo/src/omo/omo_state.py:cmd_state_sync_tasks",
            "mutation_target": ".omo/state/system.yaml (task counters + next_* projection)",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:write_system_projection_fields",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/state/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-state-sync-projection",
            "entrypoint": "omo state sync",
            "runtime_ref": "projects/omo/src/omo/omo_state.py:cmd_state_sync",
            "mutation_target": ".omo/state/health.yaml + .omo/state/system.yaml + BRIEF.md + .omo/_control/governance-data.json",
            "broker_ref": "projects/omo/src/omo/omo_ingress_state.py:sync_state_projection",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/state/",
            "mode": "brokered",
            "category": "governance_ingress",
        },
        {
            "name": "omo-audit-sync-system-projection",
            "entrypoint": "python -m omo.omo_audit_sync --apply",
            "runtime_ref": "projects/omo/src/omo/omo_audit_sync.py:apply_diff",
            "mutation_target": ".omo/state/system.yaml (whitelisted audit projection fields)",
            "broker_ref": "projects/omo/src/omo/omo_ingress.py:write_system_projection_fields",
            "delivery_artifact_root": "runtime/omo/_delivery/ingress/state/",
            "mode": "brokered",
            "category": "runtime_cache",
        },
    ]


def _mutation_surface_category_counts(items: list[dict[str, object]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        category = str(item.get("category", "unclassified"))
        counts[category] = counts.get(category, 0) + 1
    return dict(sorted(counts.items()))


def _worker_internal_write_profiles_snapshot() -> list[dict[str, object]]:
    return [
        {
            "name": "worker-dispatch",
            "runtime_ref": "projects/omo/src/omo/omo_worker_dispatch.py:dispatch_task",
            "category": "worker_internal",
            "subtype": "dispatch_runtime",
            "writes": [
                ".omo/workers/runs/*-dispatch.yaml",
                ".omo/workers/runs/*-envelope.yaml",
                ".omo/workers/runs/*-prompt.md",
                ".omo/workers/runs/*-checkpoint.md",
                ".omo/workers/runs/*-reclaim.md",
                ".omo/workers/runs/*-review.md",
                ".omo/workers/runs/*-stdout.log",
                ".omo/tasks/active/*.yaml",
            ],
            "promotion_surface": False,
            "note": "内部调度运行态；不是人类/bridge 入口",
        },
        {
            "name": "worker-task-lifecycle",
            "runtime_ref": "projects/omo/src/omo/omo_worker_dispatch.py:yield_task + _fast_track_compaction",
            "category": "worker_internal",
            "subtype": "task_lifecycle_runtime",
            "writes": [
                ".omo/workers/runs/*-dispatch.yaml",
                ".omo/tasks/planned/*.yaml",
                ".omo/tasks/archived/*.yaml",
                ".omo/_knowledge/audits/*.md",
                "runtime/omo/_delivery/ingress/tasks/*-yield-*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-archive-*.yaml",
                "runtime/omo/_delivery/ingress/audits/*.yaml",
            ],
            "promotion_surface": False,
            "note": "内部任务回退与 Fast-Track 归档链路；通过 broker 持久化",
        },
        {
            "name": "worker-self-evolution-remediation",
            "runtime_ref": "projects/omo/src/omo/omo_worker_promotion.py:_route_self_evolution_packet_to_remediation",
            "category": "worker_internal",
            "subtype": "remediation_runtime",
            "writes": [
                ".omo/tasks/planned/*.yaml",
                ".omo/tasks/remediation/*.yaml",
                ".omo/tasks/remediation-notes/*.md",
                "runtime/omo/_delivery/ingress/tasks/*-route-self-evolution-*.yaml",
            ],
            "promotion_surface": False,
            "note": "self-evolution 专用 review lane；已批但不可入 active 的包转入 remediation",
        },
        {
            "name": "worker-promotion",
            "runtime_ref": "projects/omo/src/omo/omo_worker_promotion.py:_apply_task_promotion",
            "category": "worker_internal",
            "subtype": "promotion_runtime",
            "writes": [
                ".omo/workers/runs/*-promotion-*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-promote-*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-revert-*.yaml",
                ".omo/state/system.yaml (via sync_omo_state.py)",
            ],
            "promotion_surface": True,
            "note": "内部晋升与回滚链路；task 生命周期迁移已通过 ingress broker 持久化",
        },
        {
            "name": "worker-status",
            "runtime_ref": "projects/omo/src/omo/omo_worker_status.py:update_dispatch_checkpoint",
            "category": "worker_internal",
            "subtype": "checkpoint_runtime",
            "writes": [
                ".omo/workers/runs/*-checkpoint.md",
                ".omo/workers/runs/*-dispatch.yaml",
            ],
            "promotion_surface": False,
            "note": "内部 checkpoint/lease 续写",
        },
        {
            "name": "worker-approval-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_worker_promotion.py:_request_task_promotion_approval_record + projects/omo/src/omo/omo_admission.py:request_conditional_approval",
            "category": "worker_internal",
            "subtype": "approval_runtime",
            "writes": [
                ".omo/workers/runs/*-promotion-approval-*.yaml",
                ".omo/workers/runs/*-approval.yaml",
                ".omo/_truth/task-center/proposals/*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-promotion-approval-*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-contract-request-*.yaml",
            ],
            "promotion_surface": True,
            "note": "内部审批请求与 contract-request 链路；planned/active task 补丁已通过 ingress broker 落盘",
        },
        {
            "name": "worker-rollout-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_rollout.py:accept_rollout_envelope",
            "category": "worker_internal",
            "subtype": "rollout_runtime",
            "writes": [
                ".omo/workers/runs/*-acceptance.yaml",
                ".omo/workers/runs/*-envelope.yaml",
            ],
            "promotion_surface": False,
            "note": "内部 rollout acceptance 续写",
        },
        {
            "name": "worker-experience-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_experience.py",
            "category": "worker_internal",
            "subtype": "experience_runtime",
            "writes": [
                ".omo/tasks/blocked/*.yaml",
                ".omo/_delivery/task-center/consensus/*.yaml",
                ".omo/_truth/task-center/usage-accounting.yaml",
                ".omo/_delivery/task-center/freshness/current.yaml",
                ".omo/_delivery/task-center/control/current.yaml",
                ".omo/summaries/*.md",
                "runtime/omo/_delivery/ingress/tasks/*-blocked-*.yaml",
                "runtime/omo/_delivery/ingress/tasks/*-consensus-*.yaml",
                "runtime/omo/_delivery/ingress/task-center/*.yaml",
            ],
            "promotion_surface": False,
            "note": "复杂请求桥接与 task-center truth/control 产物已通过 ingress broker 落盘；summary markdown 保留为运行时写出",
        },
        {
            "name": "worker-overlay-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_worker_promotion.py:_write_task_governance_overlay_* + _write_task_promotion_*",
            "category": "worker_internal",
            "subtype": "analytics_runtime",
            "writes": [
                ".omo/_truth/governance-overlay/roadmap.yaml",
                ".omo/_control/governance-overlay/current.yaml",
                "runtime/omo/_delivery/ingress/governance-overlay/*.yaml",
                ".omo/workers/promotion/current.yaml",
                ".omo/workers/promotion/current.md",
                ".omo/workers/promotion/readiness.yaml",
                ".omo/workers/promotion/readiness.md",
                ".omo/workers/promotion/approvals/**/current.yaml",
                ".omo/workers/promotion/approvals/**/current.md",
                ".omo/workers/governance-overlay/**/current.yaml",
                ".omo/workers/governance-overlay/**/current.md",
            ],
            "promotion_surface": False,
            "note": "governance overlay roadmap/control 已通过 ingress broker 持久化；shell current 与 approval analytics 仍为运行时快照",
        },
        {
            "name": "debt-review-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_debt.py:refresh_outputs + write_dashboard + write_review_queue + write_review_pack + projects/omo/src/omo/omo_debt_io.py:write_dashboard + write_review_queue",
            "category": "kernel_internal",
            "subtype": "governance_review_runtime",
            "writes": [
                ".omo/debt/dashboard/current.yaml",
                ".omo/debt/review-queue/current.yaml",
                ".omo/debt/reviews/current.md",
            ],
            "promotion_surface": False,
            "note": "debt review 面板与审查包由 OMO 内核直接生成；属于治理巡检输出",
        },
        {
            "name": "debt-routing-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_debt.py:refresh_outputs + write_action_packet + write_owner_routing + projects/omo/src/omo/omo_debt_io.py:write_action_packet + write_owner_routing",
            "category": "kernel_internal",
            "subtype": "governance_routing_runtime",
            "writes": [
                ".omo/debt/action-packet/current.yaml",
                ".omo/debt/action-packet/current.md",
                ".omo/debt/owner-routing/current.yaml",
                ".omo/debt/owner-routing/current.md",
            ],
            "promotion_surface": False,
            "note": "debt action packet 与 owner routing 由 OMO 内核直接生成；属于治理分发前置产物",
        },
        {
            "name": "debt-dispatch-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_debt.py:dispatch_outputs + write_dispatch_packet + projects/omo/src/omo/omo_debt_io.py:write_dispatch_packet",
            "category": "kernel_internal",
            "subtype": "governance_dispatch_runtime",
            "writes": [
                ".omo/debt/dispatch/current.yaml",
                ".omo/debt/dispatch/current.md",
                ".omo/debt/dispatch/runs/*.yaml",
                ".omo/debt/dispatch/runs/*.md",
            ],
            "promotion_surface": False,
            "note": "debt dispatch current/runs 产物由 OMO 内核直接生成；属于治理派发执行面",
        },
        {
            "name": "debt-campaign-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_debt.py:write_campaign_packet + build_selected_campaign_packet + projects/omo/src/omo/omo_debt_io.py:write_campaign_packet",
            "category": "kernel_internal",
            "subtype": "governance_campaign_runtime",
            "writes": [
                ".omo/debt/campaign/current.yaml",
                ".omo/debt/campaign/current.md",
                ".omo/debt/campaign/runs/**/current.yaml",
                ".omo/debt/campaign/runs/**/current.md",
            ],
            "promotion_surface": False,
            "note": "debt campaign current/runs 产物由 OMO 内核直接生成；属于治理专项推进面",
        },
        {
            "name": "debt-reporting-runtime",
            "runtime_ref": "projects/omo/src/omo/omo_debt.py:write_reporting_* + load_reporting_history_packet + _reporting_history_inputs + projects/omo/src/omo/omo_debt_io.py:write_reporting_*",
            "category": "kernel_internal",
            "subtype": "governance_reporting_runtime",
            "writes": [
                ".omo/debt/reporting/current.yaml",
                ".omo/debt/reporting/current.md",
                ".omo/debt/reporting/runs/**/current.yaml",
                ".omo/debt/reporting/runs/**/current.md",
                ".omo/debt/reporting/history/current.yaml",
                ".omo/debt/reporting/history/current.md",
                ".omo/debt/reporting/diff/current.yaml",
                ".omo/debt/reporting/diff/current.md",
                ".omo/debt/reporting/trend/current.yaml",
                ".omo/debt/reporting/trend/current.md",
            ],
            "promotion_surface": False,
            "note": "debt reporting/history/diff/trend 产物由 OMO 内核直接生成；属于治理报表分析面",
        },
    ]


def _worker_profile_subtype_counts(
    items: list[dict[str, object]],
) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        subtype = str(item.get("subtype", "unknown"))
        counts[subtype] = counts.get(subtype, 0) + 1
    return dict(sorted(counts.items()))
