"""C2G to Knowledge Graph (KOS) Publisher (ADR-0296 Phase C).

Transforms C2G OutcomeTracker and PredictiveEngine metrics into structured Markdown
knowledge cards and emits them via Agora /v1/tools/call (publish_event) or HTTP API.
Features graceful non-blocking offline degradation for high availability and offline testing.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any

import httpx

logger = logging.getLogger("c2g.knowledge_publisher")

_DEFAULT_AGORA_ENDPOINT = os.environ.get("AGORA_HTTP_ENDPOINT", "http://127.0.0.1:7422")
_DEFAULT_COCKPIT_KNOWLEDGE_URL = os.environ.get(
    "COCKPIT_KNOWLEDGE_URL", "http://127.0.0.1:8000/api/knowledge/put"
)


def _emit_via_network(
    card_slug: str,
    title: str,
    content: str,
    tags: list[str],
    category: str = "c2g-insight",
    agora_endpoint: str | None = None,
    cockpit_knowledge_url: str | None = None,
    timeout: float = 1.5,
) -> dict[str, Any]:
    """Emit knowledge card via Agora MCP publish_event or fallback HTTP endpoint.

    Gracefully degrades to offline status without raising exceptions.
    """
    endpoint = agora_endpoint or _DEFAULT_AGORA_ENDPOINT
    put_url = cockpit_knowledge_url or _DEFAULT_COCKPIT_KNOWLEDGE_URL

    payload = {
        "slug": card_slug,
        "title": title,
        "content": content,
        "tags": tags,
        "category": category,
        "metadata": {"source": "c2g.knowledge_publisher", "adr": "0296"},
    }

    # Strategy 1: Try Agora /v1/tools/call -> publish_event (bos://memory/events/card_updated)
    try:
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(
                f"{endpoint.rstrip('/')}/v1/tools/call",
                json={
                    "tool": "publish_event",
                    "arguments": {
                        "event_type": "bos://memory/events/card_updated",
                        "payload": payload,
                    },
                },
            )
            if resp.status_code == 200:
                data = resp.json()
                return {
                    "status": "ok",
                    "channel": "agora_mcp",
                    "slug": card_slug,
                    "response": data,
                }
    except Exception as e:  # noqa: BLE001  (fallback to next strategy)
        logger.debug("Agora /v1/tools/call unreachable: %s", e)

    # Strategy 2: Fallback try Cockpit HTTP /api/knowledge/put
    try:
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(put_url, json=payload)
            if resp.status_code in (200, 201):
                data = resp.json()
                return {
                    "status": "ok",
                    "channel": "http_put",
                    "slug": card_slug,
                    "response": data,
                }
    except Exception as e:  # noqa: BLE001  (offline degradation)
        logger.debug("Cockpit HTTP /api/knowledge/put unreachable: %s", e)

    # Offline degradation
    return {
        "status": "degraded_offline",
        "slug": card_slug,
        "message": "Both Agora MCP and Cockpit HTTP endpoints unreachable; card generated offline without blocking.",
        "payload": payload,
    }


def publish_outcome_card(
    pitch_id: str,
    outcome_data: dict[str, Any],
    agora_endpoint: str | None = None,
    cockpit_knowledge_url: str | None = None,
) -> dict[str, Any]:
    """Publish a single pitch outcome record as a knowledge card."""
    card_slug = f"c2g-outcome-{pitch_id}".lower().replace("_", "-")
    title = f"C2G Outcome Report: {pitch_id}"

    success_score = outcome_data.get("success_score", 0.0)
    generated = len(outcome_data.get("generated_tasks", []))
    completed = len(outcome_data.get("completed_tasks", []))
    failed = len(outcome_data.get("failed_tasks", []))
    lessons = outcome_data.get("lessons_learned", [])
    status_str = outcome_data.get("status", "active")

    lines = [
        f"# C2G Strategic Pitch Outcome: `{pitch_id}`",
        "",
        "## Performance Overview",
        f"- **Status**: `{status_str}`",
        f"- **Success Score**: **{success_score:.2%}**",
        f"- **Tasks Summary**: {completed} Completed / {failed} Failed / {generated} Generated",
        "",
        "## Lessons Learned",
    ]
    if lessons:
        for item in lessons:
            lines.append(f"- {item}")
    else:
        lines.append("- *No specific lessons recorded yet.*")

    lines.extend(
        [
            "",
            "---",
            "*Generated by C2G outcome_tracker & knowledge_publisher (ADR-0296)*",
        ]
    )
    content = "\n".join(lines)

    tags = ["c2g", "outcome", "backtest", f"pitch-{pitch_id}"]
    return _emit_via_network(
        card_slug=card_slug,
        title=title,
        content=content,
        tags=tags,
        category="c2g-outcome",
        agora_endpoint=agora_endpoint,
        cockpit_knowledge_url=cockpit_knowledge_url,
    )


def publish_predictive_card(
    report_data: dict[str, Any],
    agora_endpoint: str | None = None,
    cockpit_knowledge_url: str | None = None,
) -> dict[str, Any]:
    """Publish an aggregate predictive and risk heatmap report as a knowledge card."""
    card_slug = "c2g-predictive-risk-heatmap"
    title = "C2G Predictive Governance & Risk Heatmap"

    backtest = report_data.get("backtest", {})
    forecast = report_data.get("forecast", {})
    heatmap_md = report_data.get("heatmap_markdown", "")

    mean_score = backtest.get("mean_success_score", 0.0)
    count = backtest.get("pitch_count", 0)

    lines = [
        "# C2G Strategic Predictive Report & Risk Heatmap",
        "",
        "## Portfolio Backtest Metrics",
        f"- **Total Tracked Pitches**: `{count}`",
        f"- **Mean Success Score**: **{mean_score:.2%}**",
        f"- **Completed Tasks**: `{backtest.get('completed_tasks', 0)}`",
        f"- **Failed Tasks**: `{backtest.get('failed_tasks', 0)}`",
        "",
        "## Time-Series Forecast",
        "```json",
        json.dumps(forecast, indent=2, ensure_ascii=False),
        "```",
        "",
        "## Strategic Risk Heatmap",
        heatmap_md or "*No heatmap generated.*",
        "",
        "---",
        "*Generated by C2G PredictiveEngine (ADR-0185, ADR-0296)*",
    ]
    content = "\n".join(lines)

    tags = ["c2g", "predictive", "risk", "governance"]
    return _emit_via_network(
        card_slug=card_slug,
        title=title,
        content=content,
        tags=tags,
        category="c2g-predictive",
        agora_endpoint=agora_endpoint,
        cockpit_knowledge_url=cockpit_knowledge_url,
    )
