"""OMO Sovereignty (W2-01 / W2-02) — Principal/Role/Responsibility/RoleAssignment + Mandates.

Local-only sovereignty governance on top of the causal event ledger:

- W2-01 models: :class:`Principal`, :class:`Role`, :class:`Responsibility`,
  :class:`RoleAssignment` with strict literal prefix ids and monotonic versions;
- W2-02 models: :class:`MandateManager` for DelegationMandate grant/revoke/admit;
- every model is validated, immutable and versioned; each mutation persists
  exactly one lifecycle event carrying the aggregate snapshots;
- every write goes through ``LedgerBroker.append`` and every query replays
  the ledger for a single principal_id;
- admission is pure read / pure decision and never appends.

Explicitly out of scope: PDP / PEP / W2-04 projections / Constitution /
any Agora or remote interface.
"""

from omo.sovereignty.mandates import (
    EVT_MANDATE_GRANT,
    EVT_MANDATE_REVOKE,
    MANDATE_PRODUCER,
    MANDATE_SPACE_ID,
    REASON_ALLOW,
    REASON_APPROVAL_REQUIRED,
    REASON_AUTONOMY_FORBIDS,
    REASON_BUDGET_EXCEEDED,
    REASON_CAPABILITY_OUT_OF_SCOPE,
    REASON_DISCLOSURE_MISMATCH,
    REASON_EPISODE_MISMATCH,
    REASON_EXECUTOR_MISMATCH,
    REASON_HUMAN_ADJUDICATION_REQUIRED,
    REASON_MANDATE_EXPIRED,
    REASON_MANDATE_NOT_FOUND,
    REASON_MANDATE_NOT_YET_VALID,
    REASON_MANDATE_REVOKED,
    REASON_PER_ACTION_APPROVAL_REQUIRED,
    REASON_PRINCIPAL_MISMATCH,
    REASON_RESPONSIBILITY_STALE,
    REASON_RISK_CEILING_EXCEEDED,
    REASON_ROLE_CONTEXT_STALE,
    REASON_SUGGEST_ONLY,
    AdmissionResult,
    IllegalMandateTransitionError,
    MandateError,
    MandateManager,
    MandateReplayError,
    MandateState,
    StaleMandateVersionError,
)
from omo.sovereignty.roles import (
    EVT_ASSIGN,
    EVT_REPLACE,
    EVT_REVOKE,
    PRODUCER,
    SPACE_ID,
    STATUS_ACTIVE,
    STATUS_REVOKED,
    IllegalTransitionError,
    InvalidIdError,
    Principal,
    Responsibility,
    Role,
    RoleAssignment,
    SovereigntyError,
    SovereigntyReplayError,
    SovereigntyService,
    SovereigntyState,
    StaleVersionError,
    generate_id,
    validate_id,
)

__all__ = [
    "EVT_ASSIGN",
    "EVT_MANDATE_GRANT",
    "EVT_MANDATE_REVOKE",
    "EVT_REPLACE",
    "EVT_REVOKE",
    "MANDATE_PRODUCER",
    "MANDATE_SPACE_ID",
    "PRODUCER",
    "REASON_ALLOW",
    "REASON_APPROVAL_REQUIRED",
    "REASON_AUTONOMY_FORBIDS",
    "REASON_BUDGET_EXCEEDED",
    "REASON_CAPABILITY_OUT_OF_SCOPE",
    "REASON_DISCLOSURE_MISMATCH",
    "REASON_EPISODE_MISMATCH",
    "REASON_EXECUTOR_MISMATCH",
    "REASON_HUMAN_ADJUDICATION_REQUIRED",
    "REASON_MANDATE_EXPIRED",
    "REASON_MANDATE_NOT_FOUND",
    "REASON_MANDATE_NOT_YET_VALID",
    "REASON_MANDATE_REVOKED",
    "REASON_PER_ACTION_APPROVAL_REQUIRED",
    "REASON_PRINCIPAL_MISMATCH",
    "REASON_RESPONSIBILITY_STALE",
    "REASON_RISK_CEILING_EXCEEDED",
    "REASON_ROLE_CONTEXT_STALE",
    "REASON_SUGGEST_ONLY",
    "SPACE_ID",
    "STATUS_ACTIVE",
    "STATUS_REVOKED",
    "AdmissionResult",
    "IllegalMandateTransitionError",
    "IllegalTransitionError",
    "InvalidIdError",
    "MandateError",
    "MandateManager",
    "MandateReplayError",
    "MandateState",
    "Principal",
    "Responsibility",
    "Role",
    "RoleAssignment",
    "SovereigntyError",
    "SovereigntyReplayError",
    "SovereigntyService",
    "SovereigntyState",
    "StaleMandateVersionError",
    "StaleVersionError",
    "generate_id",
    "validate_id",
]
